const mongoose = require('mongoose');

const ideaSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, required: true },
  description: { type: String, required: true },
  product: { type: String, required: true },
  industry: { type: String, required: true },
  targetCity: { type: String, required: true },
  targetCountry: { type: String, default: 'Pakistan' },
  targetCustomers: { type: String, required: true },
  priceMin: { type: Number, required: true },
  priceMax: { type: Number, required: true },
  currency: { type: String, default: 'PKR' },
  businessModel: { type: String, default: 'b2c' },
  stage: { type: String, default: 'idea' },
  analysis: {
    demandScore: Number,
    competitionScore: Number,
    viabilityScore: Number,
    marketSizeEstimate: Number,
    tamEstimate: Number,
    samEstimate: Number,
    somEstimate: Number,
    revenueProjection: { year1: Number, year2: Number, year3: Number },
    keyStrengths: [String],
    keyRisks: [String],
    opportunities: [String],
    suggestedPositioning: String,
    customerPersonas: [mongoose.Schema.Types.Mixed],
    marketTrends: [String],
    entryStrategy: String,
    criticalSuccessFactors: [String],
    overallVerdict: String,
    analyzedAt: Date,
  },
  swot: mongoose.Schema.Types.Mixed,
  bmc: mongoose.Schema.Types.Mixed,
  savedPitch: mongoose.Schema.Types.Mixed,
  milestones: [{
    title: String, description: String,
    dueDate: Date, completed: { type: Boolean, default: false },
    completedAt: Date,
  }],
  tags: [String],
  isPublic: { type: Boolean, default: false },
  likes: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  status: { type: String, default: 'active' },
}, { timestamps: true });

module.exports = mongoose.model('Idea', ideaSchema);
